## Pair programming Numpy

In [1]:
# antes de empezar importamos la librería de NumPy para poder trabajar con todos sus métodos. 
import numpy as np

Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [45]:
array1= np.random.randint(10, 100, size=50)
array1

array([30, 92, 32, 22, 71, 85, 40, 97, 20, 46, 77, 42, 32, 57, 26, 93, 34,
       37, 56, 16, 31, 27, 46, 29, 77, 24, 23, 57, 42, 10, 22, 37, 67, 96,
       16, 97, 39, 87, 51, 48, 32, 38, 20, 42, 52, 47, 86, 49, 83, 15])

In [46]:
array1[4:50:5]

array([71, 46, 26, 16, 77, 10, 16, 48, 52, 15])

Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [47]:
array2= np.random.randint(1, 21, size=30)
array2

array([ 4, 14,  2,  3,  6,  1,  3, 11, 10, 14, 11, 13, 10,  1, 20, 19, 12,
       11,  9, 14,  2,  4,  2, 16, 12,  7, 13,  2, 14, 12])

In [48]:
array2[::2]

array([ 4,  2,  6,  3, 10, 11, 10, 20, 12,  9,  2,  2, 12, 13, 14])

Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [70]:
array3= np.random.uniform(1,10,(4,6)).round(2)
array3

array([[9.81, 1.48, 7.96, 9.52, 9.6 , 1.62],
       [7.96, 3.97, 9.45, 1.16, 5.96, 5.51],
       [2.71, 8.68, 6.6 , 8.47, 1.01, 1.76],
       [3.18, 6.11, 5.74, 8.15, 7.87, 8.75]])

In [71]:
array3[3]

array([3.18, 6.11, 5.74, 8.15, 7.87, 8.75])

Crea un array NumPy 2D de forma (6, 4) con valores decimales entre 0 y 1. Accede a la segunda columna de la matriz. Los números deben estar redondeados a 2 decimales.

In [73]:
array4= np.random.rand(6,4).round(2)
array4

array([[0.78, 0.71, 0.99, 0.86],
       [0.82, 0.05, 0.14, 0.85],
       [0.2 , 0.44, 0.39, 0.69],
       [0.29, 0.08, 0.79, 0.11],
       [0.69, 0.88, 0.26, 0.93],
       [0.76, 0.43, 0.46, 0.44]])

Crea un array 1D con 30 valores enteros aleatorios entre -50 y 50. Extrae los valores negativos.

In [75]:
array5= np.random.randint(-50, 50, size=30)
array5

array([-48,  16,  19,  41, -16,  -9,  -3, -13,  34,   1,  13,   4,  14,
       -39,  16,  14,  33, -44,  41, -22, -43,  35,  11, -30,  25, -22,
         9, -50, -39,  14])

In [78]:
array5[array5<0]

array([-48, -16,  -9,  -3, -13, -39, -44, -22, -43, -30, -22, -50, -39])

Crea un array 1D con 10 valores entre 0 y 1. Redondea los decimales a 2. Obtén los elementos cuyo valor es mayor que 0.5. ¿En que posición/es están esos elementos?

In [99]:
array6= np.random.rand(10).round(2)
array6

array([0.27, 0.51, 0.42, 0.69, 0.93, 0.62, 0.76, 0.25, 0.76, 0.71])

In [107]:
mayores=array6[array6>0.5]

In [111]:
mayores

array([0.51, 0.69, 0.93, 0.62, 0.76, 0.76, 0.71])

In [117]:
index = np.where(array6 > 0.5)[0]
index

array([1, 3, 4, 5, 6, 8, 9])

In [108]:
index = np.where(array6 == mayores)
index

/tmp/ipykernel_337/919921901.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  index = np.where(array6 == mayores)


(array([], dtype=int64),)

Crea un array 1D con 40 valores del 1 al 100 (ambos incluidos). Obtén los elementos que son divisibles por 3 y por 4.

In [120]:
array7= np.random.randint(1, 100, (40))
array7

array([72, 93, 80, 80,  1, 95, 59, 83, 44, 81, 14, 14, 24, 62, 19, 91, 16,
       65, 51, 33, 78, 46, 17, 42, 88, 83, 77, 43, 51, 90,  5, 81, 78, 78,
        4, 59,  4,  6, 52, 54])

In [123]:
array8= np.random.rand(1, 100, (40)).round(2)
array8

array([[[0.32, 0.56, 0.57, ..., 0.79, 0.59, 0.75],
        [1.  , 0.79, 0.54, ..., 0.57, 0.45, 0.99],
        [0.84, 0.03, 0.13, ..., 0.87, 0.31, 0.31],
        ...,
        [0.2 , 0.16, 0.85, ..., 0.41, 0.93, 0.22],
        [0.35, 0.97, 0.26, ..., 0.33, 0.99, 0.23],
        [0.08, 0.05, 0.99, ..., 0.8 , 0.77, 0.83]]])

In [131]:
array9= np.random.uniform(1, 101, (40)).round(2)
array9

array([45.64, 89.52, 40.48, 24.68, 44.56, 31.42, 22.38, 53.35, 29.37,
       95.56, 90.97,  1.25, 42.22, 79.62, 72.68, 11.26, 30.65, 78.43,
       49.7 ,  7.57, 74.38, 60.96, 89.64,  5.83, 70.82, 60.3 , 56.21,
       57.01, 43.69, 79.43, 55.55,  7.93, 21.42, 25.06, 48.83, 73.76,
       35.79, 34.28,  9.17, 45.99])

In [132]:
array9[(array9 % 3 ==0)&(array9 % 4 ==0)]

array([], dtype=float64)


BONUS: Crea un array 3D de forma (2, 3, 5) y 50 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

In [136]:
array10 = np.random.randint(1, 101, (2,3,5))
array10

array([[[57,  5, 47, 19, 61],
        [51, 15, 55, 12,  3],
        [ 6, 28, 81, 94, 67]],

       [[72,  1, 89, 77, 29],
        [63, 78,  2, 96, 44],
        [54, 85, 66, 15, 94]]])

In [ ]:
array11 = np.random.randint(0, 101, size=(2, 3, 5))

In [138]:
array11=np.arange(1,101,(50)).reshape(2,3,5)
array11

ValueError: cannot reshape array of size 2 into shape (2,3,5)

Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). 
Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.


In [146]:
array_3D = np.random.randint(1, 101, (2,3,4))
array_3D

array([[[58, 26, 25, 18],
        [31, 15, 38, 28],
        [45, 18,  7, 16]],

       [[78, 74, 85, 14],
        [78, 66, 31, 60],
        [23, 57, 39, 45]]])

In [147]:
array_2d = array_3D.reshape(-1, 4)
array_2d

array([[58, 26, 25, 18],
       [31, 15, 38, 28],
       [45, 18,  7, 16],
       [78, 74, 85, 14],
       [78, 66, 31, 60],
       [23, 57, 39, 45]])

Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 60 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

In [153]:
array_ = np.random.randint(2, 60, (3,4,5))
array_

array([[[40, 58, 37, 39, 40],
        [17, 30, 14, 45, 41],
        [11, 12, 41,  4, 53],
        [57, 23, 42, 17, 25]],

       [[ 5, 35, 43, 55, 17],
        [24, 55, 53, 58, 45],
        [13,  7, 35, 13, 21],
        [33, 12, 26, 54, 24]],

       [[25, 30, 57, 17, 47],
        [ 7,  8,  8, 16, 56],
        [23, 29,  3,  3, 31],
        [58,  4, 21, 32,  5]]])

In [159]:
array_2 = array_.reshape(-10, 5)
array_2

array([[40, 58, 37, 39, 40],
       [17, 30, 14, 45, 41],
       [11, 12, 41,  4, 53],
       [57, 23, 42, 17, 25],
       [ 5, 35, 43, 55, 17],
       [24, 55, 53, 58, 45],
       [13,  7, 35, 13, 21],
       [33, 12, 26, 54, 24],
       [25, 30, 57, 17, 47],
       [ 7,  8,  8, 16, 56],
       [23, 29,  3,  3, 31],
       [58,  4, 21, 32,  5]])


Crea un array 3D de forma (4, 3, 2) con valores aleatorios entre 0 y 1. Utiliza reshape para convertirlo en un array 2D.

In [161]:
arr= np.random.rand(4, 3, 2)
arr

array([[[0.21495822, 0.85369961],
        [0.62910654, 0.36977428],
        [0.18200535, 0.93589959]],

       [[0.52262135, 0.51034077],
        [0.40182115, 0.11998769],
        [0.30927249, 0.1742036 ]],

       [[0.67895191, 0.42788189],
        [0.61915539, 0.54451934],
        [0.17573524, 0.79921625]],

       [[0.26048733, 0.18922853],
        [0.51024543, 0.46522255],
        [0.57797136, 0.3846472 ]]])

In [162]:
arra = arr.reshape(-10, 2)
arra

array([[0.21495822, 0.85369961],
       [0.62910654, 0.36977428],
       [0.18200535, 0.93589959],
       [0.52262135, 0.51034077],
       [0.40182115, 0.11998769],
       [0.30927249, 0.1742036 ],
       [0.67895191, 0.42788189],
       [0.61915539, 0.54451934],
       [0.17573524, 0.79921625],
       [0.26048733, 0.18922853],
       [0.51024543, 0.46522255],
       [0.57797136, 0.3846472 ]])

Ejercicios con transpose:
Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

In [163]:
array_ = np.random.randint(2, 60, (3,4,5))
array_

array([[[12, 44, 13, 34, 58],
        [27, 58,  4,  5,  3],
        [37, 10, 30, 43,  3],
        [31, 41, 25,  5, 52]],

       [[ 4, 35, 15, 14, 29],
        [32, 12, 25, 50, 23],
        [42, 14, 45, 24, 56],
        [56, 48, 51,  8, 47]],

       [[49, 14, 29, 57, 42],
        [13, 16, 11, 52,  2],
        [19, 12, 13, 49, 20],
        [31, 48, 55, 42, 59]]])

In [165]:
transponer=np.transpose(array_)#(5,4,3)
transponer

array([[[12,  4, 49],
        [27, 32, 13],
        [37, 42, 19],
        [31, 56, 31]],

       [[44, 35, 14],
        [58, 12, 16],
        [10, 14, 12],
        [41, 48, 48]],

       [[13, 15, 29],
        [ 4, 25, 11],
        [30, 45, 13],
        [25, 51, 55]],

       [[34, 14, 57],
        [ 5, 50, 52],
        [43, 24, 49],
        [ 5,  8, 42]],

       [[58, 29, 42],
        [ 3, 23,  2],
        [ 3, 56, 20],
        [52, 47, 59]]])


Utiliza el array 3D del ejercicio 3 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 2, 4).

In [166]:
arr= np.random.rand(4, 3, 2) #indices (0,1,2)
arr

array([[[0.00194194, 0.54447809],
        [0.06603692, 0.27401333],
        [0.54906457, 0.21673869]],

       [[0.40526172, 0.72554155],
        [0.97831753, 0.30867888],
        [0.71877632, 0.4842085 ]],

       [[0.26581326, 0.45414021],
        [0.24502485, 0.78698498],
        [0.93051735, 0.997849  ]],

       [[0.96995519, 0.22988931],
        [0.4389974 , 0.23360087],
        [0.61869345, 0.46360999]]])

In [168]:
trans=np.transpose(arr,(1, 2, 0)) #(3, 2, 4) 
trans

array([[[0.00194194, 0.40526172, 0.26581326, 0.96995519],
        [0.54447809, 0.72554155, 0.45414021, 0.22988931]],

       [[0.06603692, 0.97831753, 0.24502485, 0.4389974 ],
        [0.27401333, 0.30867888, 0.78698498, 0.23360087]],

       [[0.54906457, 0.71877632, 0.93051735, 0.61869345],
        [0.21673869, 0.4842085 , 0.997849  , 0.46360999]]])

## Funciones Aritméticas y Estadísticas:
Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.


Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

Si el valor del array es igual que la media, se reemplaza por "A".

Si el valor del array es mayor que la media, se reemplaza por "B".

Si el valor del array es menor que la media, se reemplaza por "C".

Si el valor es igual que el máximo, se reemplaza por "D".

Si el valor es igual que el mínimo, se reemplaza por "E".

In [28]:
arr=np.random.random_sample((2,3,5)).round(1)
arr

array([[[0.2, 0.2, 1. , 0.8, 0.1],
        [0.1, 1. , 0.1, 0.5, 0.4],
        [0. , 0.6, 1. , 0. , 0.2]],

       [[0.8, 0.8, 0.5, 0.8, 0.5],
        [0.5, 0.5, 0. , 1. , 0.8],
        [0.8, 0.2, 0.6, 0.8, 0. ]]])

In [29]:
media= np.mean (arr)
media

0.4933333333333334

In [30]:
max= np.max (arr)
max

1.0

In [31]:
min= np.min (arr)
min

0.0

In [32]:
#Accedemos a la primera matriz, primera fila, primer elemento
arr[0][0][0] > media

False

In [33]:
#forma del arr
arr.shape

(2, 3, 5)

In [34]:
#Tenemos que ver todas las posiciones del arr
arr[0][0][3] > media

True

In [55]:
#Tenemos que convertir el array en letras, OJO! solo admite un valor
#Array vacio con la misma forma de (arr) y con un tipo de dato str
vacio=np.empty_like(arr,dtype=str)
vacio

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

In [36]:
for matriz in range (2):
    print(arr[matriz])

[[0.2 0.2 1.  0.8 0.1]
 [0.1 1.  0.1 0.5 0.4]
 [0.  0.6 1.  0.  0.2]]
[[0.8 0.8 0.5 0.8 0.5]
 [0.5 0.5 0.  1.  0.8]
 [0.8 0.2 0.6 0.8 0. ]]


In [52]:
#para acceder a todos los elemntos podemos automatizarlo accediendo a los niveles del shape
#vamos a generar los 3 indices
for matriz in range (arr.shape[0]):
    for fila in range (arr.shape[1]):
        for col in range(arr.shape[2]):
            print(arr[matriz][fila][col])
            print('----------')

0.2
----------
0.2
----------
1.0
----------
0.8
----------
0.1
----------
0.1
----------
1.0
----------
0.1
----------
0.5
----------
0.4
----------
0.0
----------
0.6
----------
1.0
----------
0.0
----------
0.2
----------
0.8
----------
0.8
----------
0.5
----------
0.8
----------
0.5
----------
0.5
----------
0.5
----------
0.0
----------
1.0
----------
0.8
----------
0.8
----------
0.2
----------
0.6
----------
0.8
----------
0.0
----------


In [53]:
for matriz in range (arr.shape[0]):
    for fila in range (arr.shape[1]):
        for col in range(arr.shape[2]):
            if arr[matriz][fila][col]== max:
                vacio[matriz][fila][col]="D"
            elif arr[matriz][fila][col]== min:
                vacio[matriz][fila][col]="E"
            elif arr[matriz][fila][col]== media:
                vacio[matriz][fila][col]="A"
            elif arr[matriz][fila][col]> media:
                vacio[matriz][fila][col]="B"
            elif arr[matriz][fila][col]< media:
                vacio[matriz][fila][col]="C"

In [54]:
vacio

array([[['C', 'C', 'D', 'B', 'C'],
        ['C', 'D', 'C', 'B', 'C'],
        ['E', 'B', 'D', 'E', 'C']],

       [['B', 'B', 'B', 'B', 'B'],
        ['B', 'B', 'E', 'D', 'B'],
        ['B', 'C', 'B', 'B', 'E']]], dtype='<U1')